version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # Cambia por tu password
      MYSQL_DATABASE: zenmediclick
    volumes:
      - mysql-data:/var/lib/mysql  # Persistencia
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql  # Datos iniciales
    ports:
      - 3306:3306

  backend:
    build: ./
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DB_URL=mysql+pymysql://root:rootpass@db:3306/zenmediclick

  frontend:
    build: ./
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - 3000:3000

volumes:
  mysql-data: